source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'Decodable', '~> 0.4'


target 'HelloTrello_Example', :exclusive => true do
  pod 'HelloTrello', :path => '../'
end

target 'HelloTrello_Tests', :exclusive => true do
  pod 'HelloTrello', :path => '../'
end
